### ISSUE TITLE
Lazy loading not working as intended

### ISSUE THREAD

**Issue by carlos1162** [CodyHouse/cd-lazy-load-changelog#6]
As you can see even in your demo that the demo says only 1 image has been loaded but in the network tab all 7 images have loaded. It looks like regardless of threshold there is something missing that is loading everything at once.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/7085034/200953012-fd274cf2-f52d-4f44-9a35-8d7a311e258b.png">

**Comment by claudia-romano** [comment]
Hi Carlos, please check out this issue:
https://github.com/CodyHouse/cd-lazy-load-changelog/issues/5

You can check if the browser you are using supports lazy loading. In this case there's no JS running (the component uses the browser native lazy loading behaviour). More info here:
https://codyhouse.co/ds/components/info/lazy-load

**Comment by carlos1162** [comment]
Hi Claudia,

I'm using it on a landing page and was testing in the latest version of Chrome.

**Comment by claudia-romano** [comment]
Thanks for the info!
Chrome does support the lazy-loading property:
https://caniuse.com/loading-lazy-attr

In this case, there's no JS running but the browser takes care of natively loading the images. 

So this is the way Chrome handles lazy-loading of the images. If you try adding some additional content before those images, you'll see that some are not loaded immediately. Please check this issue for more info: 
https://stackoverflow.com/questions/57753240/native-lazy-loading-loading-lazy-not-working-even-with-flags-enabled

I'm closing this issue since this is not related to the component. Feel free to reopen it if you find any issues. Thanks!
